# experiment description
exp_name: 'test'
n_episode: 1000

exp_policy_file_name: 'reacher_2dof_corner'
exp_demo_file_name: 'reacher_2dof_corner'
lea_policy_file_name: 'reacher_2dof_corner'
lea_demo_file_name: 'reacher_2dof_corner_copy'

# DAIL
lambda_1: 0.1

# environment description
exp_env_name: 'Reacher2DOFCorner-v0'
lea_env_name: 'Reacher2DOFCorner-v0'
exp_epi_len: 60
lea_epi_len: 60
exp_goal: True
exp_goal_offset: 0
exp_goal_dim: 2
lea_goal: True
lea_goal_offset: 0
lea_goal_dim: 2

# architecture description
P_hidden_layers: [64, 64, 64]
f_hidden_layers: [200, 200]
g_hidden_layers: [200, 200]
D_hidden_layers: [64, 64]

# option
# 0-element: batchnorm ('batch-norm' means we use batch normalization)
# 1-element: activation function ('relu', 'leaky-relu', 'sigmoid', 'tanh')
# 2-element: last activation function ('default' means nothing, 'sigmoid', 'tanh')
P_options: ['default', 'leaky-relu', 'default']
f_options: ['default', 'leaky-relu', 'default']
g_options: ['default', 'leaky-relu', 'default']
D_options: ['default', 'leaky-relu', 'sigmoid']


# training description
learning_rate: 0.001
epochs: 100
batch_size: 256
iter_size: 100
n_log_epi: 10
